# Base image olarak alpine'in son sürümü indirilir.
  
  FROM alpine:latest

# Apk paket yöneticisi aracılığıyla curl ve htop komutları alpine'in içine eklenir.
# Curl ve htop usr/bin klasörünün altında bulunur.

  RUN apk add --no-cache curl
  RUN apk add --no-cache htop


